### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SAM-Alert** [vaerh/docker-routeros#13]
I am having error below. Did you really update your final code?

Connecting to download.mikrotik.com (159.148.172.226:443)
wget: server returned error: HTTP/1.1 404 Not Found

**Comment by vaerh** [comment]
Hi! Can you describe your problem more fully? This image was used a few minutes ago for automated testing of the terraform provider.

**Comment by SAM-Alert** [comment]
> Hi! Can you describe your problem more fully? This image was used a few minutes ago for automated testing of the terraform provider.

I ran your image file which you compiled at hub.docker. I like your work. So I decided to compiled your code and error above occurred. I managed to correct the path. but after creating docker image it doesn't behave like your compiled code. Can you help me with that?
Actually I am looking for container with more than five ethernet interfaces which could run on Routerboard.

**Comment by vaerh** [comment]
You can just change the entry point when you start this container:
... --entrypoint /routeros/entrypoint_for_docker_8interfaces.sh vaerhme/routeros:latest

**Comment by vaerh** [comment]
But, answering your first question, the manufacturer changed the name of the VDI image. I'll fix it soon.

**Comment by SAM-Alert** [comment]
> 

thanks
I'll keep you posted on the progress.

**Comment by vaerh** [comment]
![Process with debugging](https://user-images.githubusercontent.com/64400271/220188680-fd16c96f-f976-4378-92d0-cba0722ffb9f.png)
Please try to build the container again!

**Comment by SAM-Alert** [comment]
version: "3"

services:

   routeros-7.7:
     image: ros:7.7
     privileged: true
     restart: unless-stopped
     cap_add:
       - NET_ADMIN
     devices:
       - /dev/net/tun
     ports:
       - "8291:8291"
       - "22222:22"
       - "22223:23"
       - "7777:80"
       - "8728:8728"
       - "8729:8729"
       - "28728:8728"
       - "28729:8729"

I tried to compose it using above but having error Boot failed: could not read the boot disk

**Comment by vaerh** [comment]
Working configuration:
```
version: "3"

services:
  routeros-7.7:
    image: vaerh/routeros:latest
    privileged: true
    restart: unless-stopped
    entrypoint: /routeros/entrypoint_for_docker_8interfaces.sh
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "8291:8291"
      - "22222:22"
      - "22223:23"
      - "7777:80"
      - "8728:8728"
      - "8729:8729"
      - "28728:8728"
      - "28729:8729"
```
